/**
*This file is automatically generated by Flash Builder to compile FlexUnit classes and is not intended for modification.
*Please click on the "Refresh" icon in "FlexUnit Results" view to regenerate this file.
*/

package
{
	import com.pixo.futbolbayer.view.match.PitchView;
	
	import flash.display.Sprite;
	
	public class FlexUnitCompilerApplication extends Sprite
	{
		
		private var com_pixo_futbolbayer_view_match_PitchView_obj:com.pixo.futbolbayer.view.match.PitchView;
	}
}